spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: pw
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update


